# Generated by Django 4.2.11 on 2024-04-26 15:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_host_delete_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Host',
            new_name='Post',
        ),
    ]
